@startuml

left to right direction
!define ICONURL https://raw.githubusercontent.com/jtama/plantuml-glyphs/master
!includeurl ICONURL/common.puml
!includeurl ICONURL/opentelemetry/opentelemetry.puml
!includeurl ICONURL/opentelemetry/collector.puml
!includeurl ICONURL/opentelemetry/receiver.puml
!includeurl ICONURL/opentelemetry/processor.puml
!includeurl ICONURL/opentelemetry/exporter.puml
!includeurl ICONURL/k8s/kubernetes.puml
!includeurl ICONURL/k8s/pod.puml
!include <logos/prometheus>
!include <logos/grafana>


KUBERNETES("K8S","Kubernetes", node) {
    POD("POD", "App 1") {
        COLLECTOR("SIDE_COL", "Side car", rectangle, DarkSeaGreen)
    }
    POD("POD2", "App 2") {
        COLLECTOR("SIDE_COL2", "Side car", rectangle, DarkSeaGreen)
    }
    COLLECTOR("COLLECTOR", "Main collector")
    COLLECTOR <-[#DarkSeaGreen]- SIDE_COL : Metrics
    SIDE_COL2 -[#DarkSeaGreen]-> COLLECTOR : Metrics
    database "<$prometheus>\nPrometheus" as PROM
    COLLECTOR <-up- PROM : Metrics
    rectangle "<$grafana>\nGrafana" as GRAFANA
    PROM <-- GRAFANA
}

skinparam{
   RectangleBorderThickness<<OTEL COLLECTOR>> 2
}

skinparam{
   RectangleBorderThickness<<K8S POD>> 2
}

@enduml
