= README

=== Plan
Présentation succinte d'opentelemetry 3 minutes
Contexte et contrainte de la mise en place (Application Quarkus, déploiement dans un OKD, on ne touche pas au code) 2 minutes
Déploiement d'un collecteur (en mode Deployment) 1 minutes
Mise en place de la collecte de métriques 5 minutes
Mise en place de la collecte de trace 5 minutes
Refacto en passant par l'opérateur et mise en place de sidecar 5 minutes
Mise en place de la collecte de log 5 minutes
Refacto et mise en place d'un daemonset 5 minutes
Ajout d'attribut pour autoriser la correlation 5 minutes
Refacto encore pour utiliser la sémantique OpenTelemetry 5 minutes
Conclusion 3 minutes


Mettre en couleur les nouveautés dans les diags plantuml.

=== Génération

Depuis le répertoire racine du projet :

[source,bash]
----
docker container run --rm -it -v $(pwd):/documents  cds-bdx-docker.repo-nf.groupeonepoint.com/gop-asciidoctor:1.18 gop-reveal index.adoc
----

=== Accéder au slides

[source,bash]
----
docker container run --rm -d -p 8080:80 -v $(pwd):/usr/share/nginx/html nginx
----


Licence

Changer la présentation du chef de projet et sa demande pour préciser le lien avec l'observabilité.

Ajouter un screen sur les logs. Regarder la pseudonimisation.

Slide conclusion.


