apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
spec:
  mode: daemonset
  hostNetwork: false
  serviceAccount: daemonset-collector
  securityContext:
    privileged: true
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
  volumeMounts:
    - name: varlog
      mountPath: /var/log
  config: |
    receivers:
      filelog:
        // On verra ça après 
    processors:
        // ça aussi
    exporters:
      logging:
        logLevel: debug
      loki:
        endpoint: GRÜÜÜÜÜÜÜÜ
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [attributes, transform]
          exporters: [logging, loki]

