apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: main-collector
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: main-collector
spec:
  mode: deployment
  serviceAccount: collector
  image: docker.io/otel/opentelemetry-collector-contrib:0.63.0
  ports:
      - name: collected-metrics
        protocol: TCP
        port: 9090
        targetPort: 9090
      - name: otel-metrics
        protocol: TCP
        port: 8888
        targetPort: 8888
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 6
          http:
    processors:
      batch:

      memory_limiter:
        check_interval: 5s
        limit_mib: 1500
        spike_limit_mib: 512

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
          labels:
            - tag_name: service.namespace
              key: app.kubernetes.io/part-of
              from: pod
            - tag_name: service.name
              key: app.kubernetes.io/name
              from: pod
            - tag_name: service.version
              key: app.kubernetes.io/version
              from: pod
      attributes:
        actions:
          - key: service.instance.id
            action: upsert
            from_attribute: k8s.pod.name
          - key: instance
            action: upsert
            from_attribute: k8s.pod.name
          - key: application
            action: upsert
            from_attribute: service.name
    exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
      logging:
        loglevel: debug
      prometheus:
        endpoint: :9090
        resource_to_telemetry_conversion:
          enabled: true
    service:
      telemetry:
        logs:
          level: info
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, k8sattributes, attributes, memory_limiter]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch, k8sattributes, attributes, memory_limiter]
          exporters: [otlp]
