apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-collector
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/name: sidecar-collector
spec:
  mode: sidecar
  resources:
    requests:
      memory: 50Mi
      cpu: 10m
    limits:
      memory: 100Mi
      cpu: 100m
  env:
    - name: OTEL_SERVICE_INSTANCE_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: module
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/name']
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.instance.id=$(OTEL_SERVICE_NAME),application=$(module)"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: ${module}
              scrape_interval: 5s
              metrics_path: '/q/metrics'
              scheme: http
              static_configs:
                - targets: ['localhost:8080']
                  labels:
                    instance: ${OTEL_SERVICE_NAME}
    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        limit_mib: 1500
        spike_limit_mib: 512
      resourcedetection:
        detectors: [env]
        timeout: 2s
        override: false
      attributes:
        actions:
          - key: application
            action: upsert
            from_attribute: k8s.module.name
    exporters:                                                                                                                                                                                                                               
      otlp:                                                                                                                                                                                                                                  
        endpoint: main-collector-collector.<insert-your-namespace-here>
        tls:                                                                                                                                                                                                                                 
          insecure: true
    service:                                                                                                                                                                                                                                
      pipelines:                                                                                                                                                                                                                             
        metrics:                                                                                                                                                                                                                             
          receivers: [prometheus]                                                                                                                                                                                                            
          processors: [batch, memory_limiter, resourcedetection, attributes]                                                                                                                                                                                 
          exporters: [otlp]
        traces:                                                                                                                                                                                                                              
          receivers: [otlp]                                                                                                                                                                                                                  
          processors: [batch, memory_limiter, resourcedetection, attributes]                                                                                                                                                                                 
          exporters: [otlp]
